### ISSUE TITLE
Question about the calculation of the chromaticities of primaries

### ISSUE THREAD

**Issue by heinemannj** [ha5dzs/colour_sensor_primary_calculator#2]
Can you please clarify if the following calculation in your mathlab script is really right or needs to be corrected as below:

https://github.com/ha5dzs/colour_sensor_primary_calculator/blob/master/find_chromaticity_of_primaries.m

![image](https://user-images.githubusercontent.com/3251642/110951904-e2717300-8345-11eb-93a0-49badfc80517.png)

https://github.com/ha5dzs/colour_sensor_primary_calculator/blob/master/primaries.txt

![image](https://user-images.githubusercontent.com/3251642/110952455-89eea580-8346-11eb-901e-f089b1c3fd54.png)

Based on my understanding it should like the following:

```
%% Calculate chromaticity for the primaries.

red.x = red.X / (red.X + red.Y + red.Z);
red.y = red.Y / (red.X + red.Y + red.Z);

green.x = green.X / (green.X + green.Y + green.Z);
green.y = green.Y / (green.X + green.Y + green.Z);

blue.x = blue.X / (blue.X + **blue.Y** + blue.Z);
blue.y = blue.Y / (blue.X + **blue.Y** + blue.Z);

```
```
The gamut is as follows:

Red: X =   46.325639, Y = 30.443097, Z = 2.733987, x = 0.582692, y = 0.382919, z =   0.034389
Green: X =   23.262626, Y = 43.174561, Z = 15.695279, x = 0.283233, y = 0.525670, z =   0.191097
Blue: X =   16.387758, Y = 15.210409, Z = 53.800513, x = 0.191897, y = 0.178111, z =   0.629992
```

**Comment by ha5dzs** [comment]
Yep, you are absolutely right, that should indeed be blue. Would you like to do a pull request?

**Comment by ha5dzs** [comment]
Pull request merged, thank you!
